using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Data {
    public const int categories = 8;
    public static double[,] itemsPrices = new double[categories, 5] { { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }, { 6060, 100, 57.5, 5570, 12 }};
    public static string[,] spriteNames = new string[categories, 5] { { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" }, { "01", "02", "03", "04", "05" } };
    public static string[,] itemsTitles = new string[categories, 5] { { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" }, { "PS4 white", "Xbox special", "ALien wear machine", "PS3 used", "Sonic game" } };
    public static string[] directories = new string[categories] { "Gaming/", "Gaming/", "Gaming/", "Gaming/", "Gaming/", "Gaming/", "Gaming/", "Gaming/"};
    public static int[] lengths = new int[categories] { 5,5,5,5,5,5,5,5 };

    //24 item
    public static Dictionary<string, string>[] AisleDate = new Dictionary<string, string>[]
    {
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop. Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop . powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming . Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","10000" } ,
            {"desc","Alienware Gaming Laptop live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","5000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","3000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","9000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6800" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","11000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop ...."},
            {"price","10500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics.. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring . core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","21000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop. Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop . powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming . Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","10000" } ,
            {"desc","Alienware Gaming Laptop live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","5000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","3000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","9000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6800" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","11000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop ...."},
            {"price","10500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics.. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring . core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","21000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop. Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop . powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming . Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","10000" } ,
            {"desc","Alienware Gaming Laptop live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","5000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","3000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","9000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6800" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","11000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop ...."},
            {"price","10500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics.. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring . core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","21000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop. Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop . powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming . Massive screen...."},
            {"price","1200" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","10000" } ,
            {"desc","Alienware Gaming Laptop live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","5000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","3000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","7000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","8000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","9000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","6800" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","11000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop ...."},
            {"price","10500" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics.. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring . core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","21000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        },
        new Dictionary<string, string> {
            {"prefab","Assets/Prefab/Items/Alienware 18_fbx.prefab" },
            { "title","Alienware Gaming Laptop Roaring graphics. Massive screen...."},
            {"price","1000" } ,
            {"desc","Alienware Gaming Laptop Roaring graphics. Massive screen. powerful metal body. long live battery. core i7. 16GB RAM. NVidea 5600." },
            {"rate","5" },
        }
    };

}
